### ISSUE TITLE
Images on website not loading

### ISSUE THREAD

**Issue by LuqmanAlSaba** [necropaz/IOTAWeatherNode#1]
I was following your "Weather Node" tutorial on your website, http://necropaz.github.io/weatherstation.html, and it seems that the images on the page are failing to load. Would be much appreciated if you could fix this issue! :)

Also, could I get your email or twitter in case I need to contact you again?

**Comment by necropaz** [comment]
@LukieID This tutorial is outdated. This Tutorial works with IOTA iri version <1. So I will not update the pictures because I had to rewrite all the code first ;). You can contact me in iota slack @jan_necropaz.
